name             'mariadb'
maintainer       'Kenji Okimoto'
maintainer_email 'okimoto@clear-code.com'
license          'MIT'
description      'Installs/Configures mariadb'
long_description 'Installs/Configures mariadb'
version          '0.1.0'
